---
- name: Inisiasi Infrastruktur TechEase
  hosts: localhost
  become: yes

  tasks:
    - name: Buat direktori data untuk Mailserver
      file:
        path: "/var/www/my-laravel-app/docker-data/dms/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - mail-data
        - mail-state
        - mail-config

    - name: Deploy layanan Docker
      shell: "cd /var/www/my-laravel-app && docker compose up -d"
